version: "3.4"

services:
  dashboard:
    image: "${DOCKER_IMAGE}"
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - "${S_DATA}/datasources:/etc/grafana/provisioning/datasources:rw"
      - "${S_DATA}/lib_grafana:/var/lib/grafana:rw"
      - "${S_DATA}/grafana.ini:/etc/grafana/grafana.ini:rw"
      - "${S_DATA}/dashboard:/etc/grafana/provisioning/dashboards:rw"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:3000/api/health"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s
