# https://prometheus.io/docs/guides/cadvisor/
version: '3.4'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    restart: always
    ports:
      - 127.0.0.1:8001:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
    depends_on:
      - redis
  # examine some container metrics produced by the Redis container
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M