version: "3.4"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    restart: always
    ports:
      - 8004:8080
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
